# Generated by Django 5.0 on 2023-12-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_salesPerson',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
                ('is_admin', models.BooleanField(default=False)),
                ('approved_by', models.CharField(default='', max_length=50)),
                ('approval_status', models.CharField(default='pending', max_length=50)),
                ('role', models.CharField(default='admin', max_length=15)),
            ],
        ),
    ]
