# Generated by Django 5.0 on 2023-12-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mentor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment_Questions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='null')),
                ('option_1', models.CharField(default='null', max_length=150)),
                ('option_2', models.CharField(default='null', max_length=150)),
                ('option_3', models.CharField(default='null', max_length=150)),
                ('option_4', models.CharField(default='null', max_length=150)),
                ('correct_answer', models.CharField(default='null', max_length=150)),
            ],
        ),
    ]
