# Generated by Django 4.2.4 on 2024-01-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intrestedStudent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('is_registered', models.CharField(default='pending', max_length=15)),
                ('status', models.CharField(default='null', max_length=15)),
                ('visited_on', models.DateField(default='0000-00-00', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registeredStudents',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('is_registered', models.CharField(default='pending', max_length=15)),
                ('payment_status', models.CharField(default='pending', max_length=15)),
                ('password', models.CharField(default='null', max_length=15)),
                ('auth_token', models.CharField(default='null', max_length=150)),
            ],
        ),
    ]
