# Generated by Django 5.0 on 2023-12-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='intrestedStudent',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('is_registered', models.CharField(default='pending', max_length=15)),
                ('payment_status', models.CharField(default='pending', max_length=15)),
                ('password', models.CharField(default='null', max_length=15)),
            ],
        ),
    ]
