# Generated by Django 4.2.4 on 2024-01-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intrestedstudent',
            name='status',
            field=models.CharField(default='interested', max_length=25),
        ),
    ]
